config/routes.rb
Rails.application.routes.draw do
  # Routes for admin pages
	namespace :admin do
		resources :courses, only: [:index, :show] do
			get :approve
			get :disapprove
    end
    resources :categories
  end

	# Routes for on-boarding Rails pages
	namespace :teaching do
  	resources :courses do
  		collection do
  			get :start_teaching
      end
			resources :enrollments, only: [] do
				collection do
					get :bulk_enrollment
					post :enroll_users
					get :requests
				end
				get :accept
				get :decline
			end
			resources :chapters, except: [:index] do
				resources :course_contents, except: [:index]
				resources :assignments do
					get :answers
				end
      end
  	end
  end

  match "zohoverify/verifyforzoho", to: 'home_page#verify', :via => [:get]

  devise_for :users, controllers: {
  	registrations: 'registrations',
  	sessions: 'sessions',
  	passwords: 'passwords',
  	confirmations: 'confirmations'
  }
  resources :users, only: [] do
  	collection do
      get :edit_password
      put :update_password
  		get :cancel_account
  		get :details
  		get :upload
  		put :do_upload
  	end
  end
	resources :notebooks, except: [:show] do
		resources :notes, except: [:show]
	end

  # Routes for API
  namespace :trading do
  	resources :stocks, :only => [:index, :show, :edit, :update] do
  		get :earning_date_history
  		get :price_history
  		post :import_earning_date_history
  		post :import_price_history
  		resources :analysis, only: [:index]
  		resources :traffics, only: [:index]
  	end

  	resources :sites do
  		get :static, on: :collection
  		resources :site_histories
  	end  	
  end

	namespace :api, constraints: { format: 'json' } do
		resources :courses, only: [:index, :show] do
			resources :conversations do
				collection do
					post :create_group
				end
				get :messages
				post :update_members
			end
			get :conversation_details
			post :enrollment_request
			collection do
				get :enrolled
      end
      resources :chapters, only: [] do
				resources :assignment_submissions, only: [:update] do
					get :find_or_create, on: :collection
				end
      end
    end
		resources :qualifications, only: [:index, :create, :update, :destroy]
		resources :reviews
    	resources :conversations, only: [] do
			resources :messages
		end
		resources :calls, only: [:create] do
      match '/:user_id/join/:calling_code', to: 'calls#join', on: :collection, :via => [:get, :post]
		end
		resources :users, only: [] do
			collection do
				get :current_user_info
				get '/:conversation_id/mark_messages_read', to: 'users#mark_messages_read'
			end
    end
    resources :enquiries, only: [:create]
	end
	root :to => 'home_page#index'
	mount ActionCable.server => '/cable'
	get '/*path', to: 'home_page#index', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}
end

app/models/course_content.rb
class CourseContent < ApplicationRecord
  belongs_to :chapter
  has_rich_text :description
  validates :title, :description, presence: true
end

app/controllers/teaching/assignments_controller.rb
class Teaching::AssignmentsController < Teaching::BaseController
  before_action :set_course_and_chapter
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :answers]

  def index
    @assignments = @chapter.assignments
  end

  def show
  end

  def new
    @assignment = @chapter.assignments.new
  end

  def edit
  end

  def create
    @assignment = @chapter.assignments.new(assignment_params)
    if @assignment.save
      redirect_to teaching_course_path(@course), notice: 'Assignment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to teaching_course_path(@course), notice: 'Assignment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @assignment.destroy
    redirect_to teaching_course_path(@course), notice: 'Assignment was successfully deleted.'
  end

  def answers
    @submissions = @assignment.assignment_submissions
  end

  private
  def set_assignment
    assignment_id = params[:id] || params[:assignment_id]
    @assignment = @chapter.assignments.find(assignment_id)
  end

  def assignment_params
    params.require(:assignment).permit(:question, :instructions, :points, :due_date, :chapter_id)
  end
end

app/controllers/teaching/base_controller.rb
class Teaching::BaseController < ApplicationController
	before_action :authenticate_user!

	protected
	def set_course_and_chapter
		set_owned_course
		@chapter = @course.chapters.find(params[:chapter_id])
	end
end

app/controllers/teaching/chapters_controller.rb
class Teaching::ChaptersController < Teaching::BaseController
  before_action :set_owned_course
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  def new
    @chapter = @course.chapters.new
  end

  def edit
  end

  def show
  end

  def create
    @chapter = @course.chapters.new(chapter_params)

    if @chapter.save
      redirect_to new_teaching_course_chapter_course_content_path(@course, @chapter), notice: 'Chapter was successfully created.'
    else
      render :new
    end
  end

  def update
    if @chapter.update(chapter_params)
      redirect_to new_teaching_course_chapter_course_content_path(@course, @chapter), notice: 'Chapter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    redirect_to teaching_course_path(@course), notice: 'Chapter was successfully deleted.'
  end

  private
  def set_chapter
    @chapter = @course.chapters.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:title)
  end
end

app/controllers/teaching/course_contents_controller.rb
class Teaching::CourseContentsController < Teaching::BaseController
  before_action :set_course_and_chapter
  before_action :set_course_content, only: [:show, :edit, :update, :destroy]

  def new
    @course_content = @chapter.course_contents.new
  end

  def edit
  end

  def create
    @course_content = @chapter.course_contents.new(course_content_params)

    respond_to do |format|
      if @course_content.save
        format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully created.' }
        format.json { render :show, status: :created, location: @course_content }
      else
        format.html { render :new }
        format.json { render json: @course_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course_content.update(course_content_params)
        format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_content }
      else
        format.html { render :edit }
        format.json { render json: @course_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course_content.destroy
    respond_to do |format|
      format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_course_content
      @course_content = @chapter.course_contents.find(params[:id])
    end

    def course_content_params
      params.require(:course_content).permit(:title, :description, :duration, :preview)
    end
end

app/controllers/teaching/courses_controller.rb
class Teaching::CoursesController < Teaching::BaseController
  before_action :authenticate_user!, except: [:show, :start_teaching]
  before_action :set_owned_course, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def index
    @courses = current_user.courses.includes(:category)
  end

  def show
    @course = Course.find(params[:id])
    @chapters = @course.chapters.includes(:course_contents).includes(:assignments)
  end

  def new
    @course = current_user.courses.new
  end

  def edit
  end

  def start_teaching
    if user_signed_in? && !current_user.has_qualifications?
      redirect_to REACT_ROUTES[:qualifications]
    end
  end

  def create
    @course = current_user.courses.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to new_teaching_course_chapter_path(@course), notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to new_teaching_course_chapter_path(@course), notice: 'Course was successfully updated.' }
        format.json { render json: @course, status: :updated }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to teaching_courses_url, notice: 'Course was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  def course_params
    params.require(:course).permit(:title, :body, :website, :course_for, :price, :category_id, :cover_image, :short_description, :course_highlights, :duration, :no_of_lessons, :level, :discount_percentage)
  end

  def set_categories
    @categories = Category.active
    @levels = [["All levels", ""], ["Beginner", "Beginner"], ["Advanced", "Advanced"], ["Intermediate", "Intermediate"]]
  end
end

app/controllers/teaching/enrollments_controller.rb
class Teaching::EnrollmentsController < Teaching::BaseController
  before_action :set_owned_course
  before_action :set_enroll_request, only: [:accept, :decline]

  def accept
    @enroll_request.approve
    @enroll_request.course.enroll_in_general_conversation(@enroll_request.user)
    flash[:notice] = "The enrollment request is approved."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def decline
    @enroll_request.destroy
    flash[:notice] = "The enrollment request is declined."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def bulk_enrollment

  end

  def enroll_users
    records_created = []
    records_failed = []
    params[:enroll_request].each do |key, enroll_request_params|
      enroll_request = @course.enroll_requests.create(allowed_enroll_request_params(enroll_request_params))
      if enroll_request.persisted?
        records_created << enroll_request.email
      else
        records_failed << enroll_request.email
      end
    end
    created_count = records_created.count
    flash[:notice] = "#{created_count} #{'request'.pluralize(created_count)} #{created_count == 1 ? 'is' : 'are'} sent(#{records_created.join(", ")}). #{records_failed.count} didn't succeed."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def requests
    @enroll_user_requests = @course.enroll_requests
  end

  private

  def set_enroll_request
    @enroll_request = @course.enroll_requests.find(params[:enrollment_id])
  end

  def allowed_enroll_request_params(enroll_request_params)
    enroll_request_params.permit(:full_name, :email, :phone)
  end
end

app/views/teaching/course_contents/_form.html.erb
<%= form_with(model: [:teaching, @course, @chapter, @course_content]) do |form| %>
  <% error_messages = @course_content.errors.messages %>
  <div class="pl-4 pr-4 space-top-1">
    <div class="row">
      <div class="col-sm-12 form-group">
        <label class="input-label" for="full_name"> <%= form.label :title %></label>
        <%= form.text_field :title, autofocus: true, autocomplete: "full_name", class: 'form-control', type: 'text', id: 'full_name', placeholder: 'Title' %>
        <% if error_messages[:title] %>
          <div class="field-error">
            <%= error_messages[:title][0] %>
          </div>
        <% end %>
      </div>

      <div class="col-sm-12 form-group">
        <label class="input-label" for="full_name"> <%= form.label :description %></label>
        <%= form.rich_text_area :description, autofocus: true, autocomplete: "description", type: 'text', id: 'description', placeholder: 'Detailed description about this content' %>
        <% if error_messages[:description] %>
          <div class="field-error">
            <%= error_messages[:description][0] %>
          </div>
        <% end %>
      </div>

      <div class="col-sm-12 form-group">
        <label class="input-label" for="full_name"> <%= form.label :duration %></label>
        <%= form.text_field :duration, autofocus: true, autocomplete: "duration", class: 'form-control', type: 'text', id: 'duration', placeholder: 'Duration' %>
        <% if error_messages[:duration] %>
          <div class="field-error">
            <%= error_messages[:duration][0] %>
          </div>
        <% end %>
      </div>

      <div class="col-sm-12 form-group">
        <div class="custom-control custom-checkbox">
          <input type="checkbox" id="preview" class="custom-control-input">
          <label class="custom-control-label" for="preview"><%= form.label :allow_preview %></label>
          <% if error_messages[:preview] %>
            <div class="field-error">
              <%= error_messages[:preview][0] %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row align-items-center mb-5 mt-4">
      <div class="col-6 mb-sm-0 pl-4">
        <%= link_to "Back", teaching_course_path(@course), class: 'font-size-1 font-weight-bold text-muted content-centered' %>
      </div>
      <div class="col-6 text-right">
        <%= form.submit "Save", class: "btn btn-sm btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/teaching/course_contents/_index.html.erb
<div class="border mb-2">
  <div class="card-header">
    <div class="media-body">
      <h5 class="mb-0"><i class="fas fa-book pt-1 mr-2 text-body"></i>Course Contents</h5>
    </div>
    <span>
       <a href="<%= new_teaching_course_chapter_course_content_path(@course, chapter) %>" class="btn btn-xs btn-soft-primary"  data-toggle="tooltip" data-html="true" title="Add New Content">
          <i class="fas fa-plus"></i>
        </a>
 </span>
  </div>

  <div class="">
    <!-- Body -->
    <div class="">
      <% if course_contents.present? %>
        <!-- Table -->
        <div class="table-responsive">
          <table class="table table-thead-bordered table-nowrap table-align-middle">
            <thead class="thead-light">
            <tr>
              <th>Title</th>
              <th>Duration</th>
              <th>Preview available</th>
              <th colspan="3">Action</th>
            </tr>
            </thead>
            <tbody>
              <% course_contents.each do |course_content| %>
                <tr>
                  <td><%= course_content.title %></td>
                  <td><%= course_content.duration %></td>
                  <td><%= course_content.preview? ? 'Yes' : 'No' %></td>
                  <td>
                    <a href="<%= teaching_course_chapter_course_content_path(@course, chapter, course_content) %>" class="btn btn-ghost-info btn-xs" data-toggle="tooltip" data-html="true" title="View" data-placement="top">
                      <i class="fas fa-eye"></i>
                    </a>
                    <a href="<%= edit_teaching_course_chapter_course_content_path(@course, chapter, course_content) %>" class="btn btn-ghost-info btn-xs mr-1" data-toggle="tooltip" data-html="true" title="Edit" data-placement="top">
                      <i class="fas fa-pen"></i>
                    </a>
                    <a href="<%= teaching_course_chapter_course_content_path(@course, chapter, course_content) %>" data-method="delete" data-confirm="Are you sure you want to delete this content?" class="btn btn-ghost-danger btn-xs" data-toggle="tooltip" data-html="true" title="Delete" data-placement="top">
                      <i class="fas fa-trash"></i>
                    </a>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <!-- End Table -->
        </div>
      <% else %>
        <div class="space-1">
          <figure class="max-w-8rem mx-auto">
            <img class="img-fluid" src="
            <%= asset_path("icons/icon-2.svg") %>" alt="SVG">
          </figure>
          <div class="text-center mt-2">No contents</div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/teaching/course_contents/edit.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
           <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_chapter_path(@course, @chapter) %>" class="text-light text-highlight-light"><%= @chapter.title %></a></li>
          <li class="breadcrumb-item active" aria-current="page">Edit <%= @course_content.title %></li>
        </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto mb-lg-5">
    <!-- Form -->
    <%= render 'form', course_content: @course_content %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path('components/dots-5.svg') %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>

app/views/teaching/course_contents/new.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
           <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_chapter_path(@course, @chapter) %>" class="text-light text-highlight-light"><%= @chapter.title %></a></li>
           <li class="breadcrumb-item active" aria-current="page">New Course Content</li>
        </ol>
        </nav>
      </span>
  </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto ">
    <!-- Form -->
    <%= render 'form', course_content: @course_content %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path('components/dots-3.svg') %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>

app/views/teaching/course_contents/show.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
           <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
           <li class="breadcrumb-item"><a href="<%= teaching_course_chapter_path(@course, @chapter) %>" class="text-light text-highlight-light"><%= @chapter.title %></a></li>
           <li class="breadcrumb-item active"><%= @course_content.title %></li>
          </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->
<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto">
    <div class="card-header">
      <h5><%= @course_content.title %></h5>
      <span>
         <a href="<%= teaching_course_path(@course) %>" class="btn btn-xs btn-no-focus btn-ghost-primary">
           Back
          </a>
      </span>
    </div>
    <div class="card-body">
      <form>
        <!-- Form Group -->
        <div class="row form-group">
          <label for="description" class="col-sm-3 col-form-label input-label">Description</label>

          <div class="col-sm-9">
            <%= @course_content.description %>
          </div>
        </div>
        <!-- End Form Group -->

        <!-- Form Group -->
        <div class="row form-group">
          <label for="duration" class="col-sm-3 col-form-label input-label">Duration</label>

          <div class="col-sm-9">
            <input type="text" class="form-control-plaintext" name="duration" id="duration" value="<%= @course_content.duration %>" readonly>
          </div>
        </div>
        <!-- End Form Group -->

        <!-- Form Group -->
        <div class="row form-group">
          <label for="preview" class="col-sm-3 col-form-label input-label">Preview Available</label>
          <div class="col-sm-9">
            <input type="text" class="form-control-plaintext" name="preview" id="preview" value=" <%= @course_content.preview? ? 'Yes' : 'No' %>" readonly>
          </div>
        </div>
        <!-- End Form Group -->
      </form>
    </div>
  </div>
</div>