config/routes.rb
Rails.application.routes.draw do
  # Routes for admin pages
	namespace :admin do
		resources :courses, only: [:index, :show] do
			get :approve
			get :disapprove
    end
    resources :categories
  end

	# Routes for on-boarding Rails pages
	namespace :teaching do
  	resources :courses do
  		collection do
  			get :start_teaching
      end
			resources :enrollments, only: [] do
				collection do
					get :bulk_enrollment
					post :enroll_users
					get :requests
				end
				get :accept
				get :decline
			end
			resources :chapters, except: [:index] do
				resources :course_contents, except: [:index]
				resources :assignments do
					get :answers
				end
      end
  	end
  end

  match "zohoverify/verifyforzoho", to: 'home_page#verify', :via => [:get]

  devise_for :users, controllers: {
  	registrations: 'registrations',
  	sessions: 'sessions',
  	passwords: 'passwords',
  	confirmations: 'confirmations'
  }
  resources :users, only: [] do
  	collection do
      get :edit_password
      put :update_password
  		get :cancel_account
  		get :details
  		get :upload
  		put :do_upload
  	end
  end
	resources :notebooks, except: [:show] do
		resources :notes, except: [:show]
	end

  # Routes for API
  namespace :trading do
  	resources :stocks, :only => [:index, :show, :edit, :update] do
  		get :earning_date_history
  		get :price_history
  		post :import_earning_date_history
  		post :import_price_history
  		resources :analysis, only: [:index]
  		resources :traffics, only: [:index]
  	end

  	resources :sites do
  		get :static, on: :collection
  		resources :site_histories
  	end  	
  end

	namespace :api, constraints: { format: 'json' } do
		resources :courses, only: [:index, :show] do
			resources :conversations do
				collection do
					post :create_group
				end
				get :messages
				post :update_members
			end
			get :conversation_details
			post :enrollment_request
			collection do
				get :enrolled
      end
      resources :chapters, only: [] do
				resources :assignment_submissions, only: [:update] do
					get :find_or_create, on: :collection
				end
      end
    end
		resources :qualifications, only: [:index, :create, :update, :destroy]
		resources :reviews
    	resources :conversations, only: [] do
			resources :messages
		end
		resources :calls, only: [:create] do
      match '/:user_id/join/:calling_code', to: 'calls#join', on: :collection, :via => [:get, :post]
		end
		resources :users, only: [] do
			collection do
				get :current_user_info
				get '/:conversation_id/mark_messages_read', to: 'users#mark_messages_read'
			end
    end
    resources :enquiries, only: [:create]
	end
	root :to => 'home_page#index'
	mount ActionCable.server => '/cable'
	get '/*path', to: 'home_page#index', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}
end

app/models/user.rb
class User < ApplicationRecord
    include ImageUpload
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable
    has_many :conversation_enrolled_users
    has_many :conversations, through: :conversation_enrolled_users
    has_many :enrolled_course_users
    has_many :enrolled_courses, through: :enrolled_course_users, source: :course
    has_many :messages, foreign_key: :sender_id
    has_many :user_message_notifications
    has_many :notification_messages, through: :user_message_notifications, source: :message
    has_many :courses
    has_many :enroll_requests
    has_many :calls
    has_many :qualifications
    has_many :educations
    has_many :experiences
    has_many :reviews, -> { order(created_at: :desc) }
    has_many :notebooks
    has_many :notes
    has_many :assignment_submissions
    has_one_attached :avatar_image, dependent: :destroy

    validate :acceptable_image
    validates :full_name, presence: true

    def avatar_image_urls
        resized_images(self.avatar_image)
    end

    def is_within_call_limit?
        self.calls.created_between(1.months.ago, Time.now).count < self.call_limit_per_month
    end

    def soft_delete
      update_attribute(:deleted_at, Time.current)
    end

    def active_for_authentication?
      super && !deleted_at
    end

    def has_qualifications?
        qualifications.present?
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
	def current_user_info
		render json:  current_user, include: %w[educations experiences]
	end

	def mark_messages_read
		conversation = current_user.conversations.find(params[:conversation_id])
		conversation.mark_messages_read(current_user)
		head :ok
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :_set_user

	def update_password
		if @user.update(_user_params)
			bypass_sign_in(@user)
			redirect_to root_path
		else
			render :edit_password
		end
	end

	def do_upload
		if params[:user][:file].present?
			current_user.avatar_image.attach(params[:user][:file])
		elsif params[:user][:camera].present?
			current_user.avatar_image.attach(_get_blob)
		end
		redirect_to upload_users_path
	end

	def _set_user
		@user = current_user
	end

	def _user_params
		params.require(:user).permit(:password, :password_confirmation)
	end

	def _get_blob
		ActiveStorage::Blob.create_after_upload!(
			io: StringIO.new((Base64.decode64(params[:user][:camera].split(",")[1]))),
			filename: "user.png",
			content_type: "image/png",
		)
	end
end

app/views/users/_address.html.erb
 <div id="editAddressCard" class="card mb-3 mb-lg-5">
  <div class="card-header">
    <h5 class="card-title">Address</h5>
  </div>

  <!-- Body -->
  <div class="card-body">
    <form>
      <!-- Form Group -->
      <div class="row form-group">
        <label for="streetAddress" class="col-sm-3 col-form-label input-label">Street Address</label>

        <div class="col-sm-9">
          <input type="text" class="form-control-plaintext" name="streetAddress" id="streetAddress" placeholder="Not Available" aria-label="Street Address" value="<%= current_user.street_address %>" readonly>
        </div>
      </div>
      <!-- End Form Group -->

      <!-- Form Group -->
      <div class="row form-group">
        <label for="city" class="col-sm-3 col-form-label input-label">City</label>

        <div class="col-sm-9">
          <input type="text" class="form-control-plaintext" name="city" id="city" placeholder="Not Available" aria-label="City" value="<%= current_user.city %>" readonly>
        </div>
      </div>
      <!-- End Form Group -->

      <!-- Form Group -->
      <div class="row form-group">
        <label for="state" class="col-sm-3 col-form-label input-label">State</label>

        <div class="col-sm-9">
          <input type="text" class="form-control-plaintext" name="state" id="state" placeholder="Not Available" aria-label="State" value="<%= current_user.state %>" readonly>
        </div>
      </div>
      <!-- End Form Group -->

      <!-- Form Group -->
      <div class="row form-group">
        <label for="zipCode" class="col-sm-3 col-form-label input-label">Zip code
          <i class="far fa-question-circle text-body ml-1" data-toggle="tooltip" data-placement="top" title="You can find your code in a postal address."></i></label>

        <div class="col-sm-9">
          <input type="text" class="form-control-plaintext" name="zipCode" id="zipCode" placeholder="Not Available" aria-label="Your zip code" value="<%= current_user.zip_code %>" readonly>
        </div>
      </div>
      <!-- End Form Group -->

      <!-- Form Group -->
      <div class="row form-group">
        <label for="country" class="col-sm-3 col-form-label input-label">Country</label>

        <div class="col-sm-9">
          <input type="text" class="form-control-plaintext" name="zipCode" id="country" placeholder="Not Available" aria-label="Country" value="<%= current_user.country %>" readonly>
        </div>
      </div>
      <!-- End Form Group -->

    </form>
  </div>
</div>

app/views/users/_education.html.erb
<div class="card mb-3 mb-lg-5">
  <div class="card-header">
    <h5 class="card-title">Education</h5>
    <span>
      <a href="/users/qualifications/#education" class="btn btn-xs btn-no-focus btn-primary">
        <i class="fas fa-pen mr-1"></i>
        Edit Education
      </a>
    </span>
  </div>
  <div class="card-body">
    <ul class='timeline'>
    <% current_user.educations.each do |education| %>
      <li class='education-item'>
        <span class="media-body mb-2">
            <h3 class="mt-1 mb-1">
              <%= education.name_of_institution %>, <span class='text-body h4'><%= education.year_start %> - <%= education.year_end.present? ? education.year_end : 'Present' %></span>
            </h3>
            <p class="mb-1"><%= education.title %>, <%= education.location %>, <%= education.country %> </p>
        </span>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/_experience.html.erb
<div class="card mb-3 mb-lg-5">
 	<div class="card-header">
    	<h5 class="card-title">Experience</h5> <span>
      <a href="/users/qualifications/#experience" class="btn btn-xs btn-no-focus btn-primary">
        <i class="fas fa-pen mr-1"></i>
        Edit Experience
      </a>
    </span>
  	</div>
  	<div class="card-body">
			<ul class='timeline'>
				<% current_user.experiences.each do |experience| %>
					<li class='experience-item'>
            <span class="media-body mb-2">
              <h3 class="mt-1 mb-1">
                <%= experience.name_of_institution %>, <span class='text-body h4'><%= experience.year_start %> - <%= experience.year_end.present? ? experience.year_end : 'Present' %></span>
              </h3>
              <p class="mb-1"><%= experience.title %>, <%= experience.location %>, <%= experience.country %> </p>
            </span>
					</li>
				<% end %>
			</ul>
  	</div>
</div>

app/views/users/_personal_info.html.erb
<div class="card mb-3 mb-lg-5">
  <div class="card-header">
    <h5 class="card-title">Basic info</h5>
    <span>
      <a href="<%= edit_user_registration_path %>" class="btn btn-xs btn-no-focus btn-primary">
        <i class="fas fa-pen mr-1"></i>
        Edit Profile
      </a>
    </span>
  </div>
  <div class="card-body">
    <div class="row form-group">
      <label for="firstNameLabel" class="col-sm-3 col-form-label input-label">Full name
        <i class="far fa-question-circle text-body ml-1" data-toggle="tooltip" data-placement="top" title="Displayed on public forums, such as Front."></i>
      </label>

      <div class="col-sm-9">
        <div class="input-group">
          <input type="text" class="form-control-plaintext" name="firstName" id="firstNameLabel" placeholder="Clarice" aria-label="Clarice" value="<%= current_user.full_name %>" readonly>
        </div>
      </div>
    </div>
    <!-- End Form Group -->

    <!-- Form Group -->
    <div class="row form-group">
      <label for="emailLabel" class="col-sm-3 col-form-label input-label">Email</label>

      <div class="col-sm-9">
        <input type="email" class="form-control-plaintext" name="email" id="emailLabel" placeholder="clarice@example.com" aria-label="clarice@example.com" value="<%= current_user.email %>" readonly>
      </div>
    </div>
    <!-- End Form Group -->

    <!-- Form Group -->
    <div class="js-add-field row form-group">
      <label for="phoneLabel" class="col-sm-3 col-form-label input-label">Phone</label>

      <div class="col-sm-9">
        <div class="input-group align-items-center">
          <input type="text" class="js-masked-input form-control-plaintext" name="phone" id="phoneLabel" placeholder="Not Available" aria-label="+x(xxx)xxx-xx-xx" value="<%= current_user.phone %>" readonly>
        </div>

      </div>
    </div>
    <!-- End Form Group -->

    <!-- Form Group -->
    <div class="row form-group">
      <label for="short_bio" class="col-sm-3 col-form-label input-label">BIO</label>

      <div class="col-sm-9">
        <div class="input-group align-items-center">
          <input type="text" class="js-masked-input form-control-plaintext" name="short_bio" id="short_bio" placeholder="Not Available"   value="<%= current_user.short_bio %>" readonly>
        </div>
      </div>
    </div>
    <!-- End Form Group -->

    <!-- Form Group -->
    <div class="row form-group">
      <label for="linkedin_url" class="col-sm-3 col-form-label input-label">LinkedIn Url</label>

      <div class="col-sm-9">
        <div class="input-group align-items-center">
          <input type="text" class="js-masked-input form-control-plaintext" name="linkedin_url" id="linkedin_url" placeholder="Not Available"   value="<%= current_user.linkedin_url %>" readonly>
        </div>
      </div>
    </div>
    <!-- End Form Group -->

    <!-- Form Group -->
    <div class="row form-group">
      <label for="twitter_url" class="col-sm-3 col-form-label input-label">Twitter Url</label>

      <div class="col-sm-9">
        <div class="input-group align-items-center">
          <input type="text" class="js-masked-input form-control-plaintext" name="twitter_url" id="twitter_url" placeholder="Not Available"   value="<%= current_user.twitter_url %>" readonly>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/cancel_account.html.erb
<main id="content" role="main" class="bg-light">
	<!-- Breadcrumb Section -->
	<div class="bg-navy">
		<div class="container space-1 space-top-lg-2 space-bottom-lg-3">
			<div class="row align-items-center">
				<div class="col">
					<div class="d-none d-lg-block">
						<h1 class="h2 text-white">Personal info</h1>
					</div>

					<!-- Breadcrumb -->
					<ol class="breadcrumb breadcrumb-light breadcrumb-no-gutter mb-0">
						<li class="breadcrumb-item">Account</li>
						<li class="breadcrumb-item active" aria-current="page">Delete Account</li>
					</ol>
					<!-- End Breadcrumb -->
				</div>

				<div class="col-auto">
					<div class="d-none d-lg-block">
						<a class="btn btn-soft-light" href="<%= destroy_user_session_path %>">Log out</a>
					</div>

					<!-- Responsive Toggle Button -->
					<button type="button" class="navbar-toggler btn btn-icon btn-sm rounde-circle d-lg-none"
									aria-label="Toggle navigation"
									aria-expanded="false"
									aria-controls="sidebarNav"
									data-toggle="collapse"
									data-target="#sidebarNav">
              <span class="navbar-toggler-default">
                <i class="fas fa-bars"></i>
              </span>
						<span class="navbar-toggler-toggled">
                 <i class="fas fa-times"></i>
              </span>
					</button>
					<!-- End Responsive Toggle Button -->
				</div>
			</div>
		</div>
	</div>
	<!-- End Breadcrumb Section -->

	<!-- Content Section -->
	<div class="container space-2 space-top-lg-0 mt-lg-n10">
		<div class="row">
			<div class="col-lg-3">
				<!-- Navbar -->
				<%= render "layouts/sidenav" %>
				<!-- End Navbar -->
			</div>

			<div class="col-lg-9">
				<!-- Card -->
				<div class="card">
					<div class="card-header">
						<h5 class="card-title">Delete your account</h5>
					</div>

					<!-- Body -->
					<div class="card-body">
						<p class="card-text">When you delete your account, you lose access to Front account services, and we
							permanently delete your personal data. You can cancel the deletion for 14 days.</p>

						<div class="form-group">
							<!-- Custom Checkbox -->
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input" id="deleteAccountCheckbox">
								<label class="custom-control-label" for="deleteAccountCheckbox">Confirm that I want to delete my
									account.</label>
							</div>
							<!-- End Custom Checkbox -->
						</div>

						<div class="d-flex justify-content-end">
							<%= link_to "Back", details_users_path, type: 'button', class: 'btn btn-white mr-2' %>
							<%= button_to "Delete", registration_path(@user), data: {confirm: "Are you sure you want to cancel your account?"}, method: :delete, class: "btn btn-danger transition-3d-hover" %>
						</div>
					</div>
					<!-- End Body -->
				</div>
				<!-- End Card -->
			</div>
		</div>
		<!-- End Row -->
	</div>
	<!-- End Content Section -->
</main>

app/views/users/details.html.erb
<main id="content" role="main" class="bg-light">
  <!-- Breadcrumb Section -->
  <div class="bg-navy">
    <div class="container space-1 space-top-lg-2 space-bottom-lg-3">
      <div class="row align-items-center">
        <div class="col">
          <div class="d-none d-lg-block">
            <h1 class="h2 text-white">Personal info</h1>
          </div>

          <!-- Breadcrumb -->
          <ol class="breadcrumb breadcrumb-light breadcrumb-no-gutter mb-0">
            <li class="breadcrumb-item">Account</li>
            <li class="breadcrumb-item active" aria-current="page">Personal info</li>
          </ol>
          <!-- End Breadcrumb -->
        </div>

        <div class="col-auto">
          <div class="d-none d-lg-block">
            <a class="btn btn-soft-light" href="<%= destroy_user_session_path %>">Log out</a>
          </div>

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn btn-icon btn-sm rounde-circle d-lg-none"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="sidebarNav"
                  data-toggle="collapse"
                  data-target="#sidebarNav">
              <span class="navbar-toggler-default">
                <i class="fas fa-bars"></i>
              </span>
            <span class="navbar-toggler-toggled">
                 <i class="fas fa-times"></i>
              </span>
          </button>
          <!-- End Responsive Toggle Button -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Breadcrumb Section -->

  <!-- Content Section -->
  <div class="container space-2 space-top-lg-0 mt-lg-n10">
    <div class="row">
      <div id="stickyBlockStartPoint" class="col-lg-3">
        <div class="js-sticky-block card border"
             data-hs-sticky-block-options='{
                   "parentSelector": "#stickyBlockStartPoint",
                   "breakpoint": "md",
                   "startPoint": "#stickyBlockStartPoint",
                   "endPoint": "#stickyBlockEndPoint",
                   "stickyOffsetTop": 12,
                   "stickyOffsetBottom": 12
                 }'>

          <!-- Navbar -->
          <%= render "layouts/sidenav" %>
          <!-- End Navbar -->

        </div>
      </div>

      <div class="col-lg-9">
        <%= render "users/personal_info" %>
        <%= render "users/address" %>
        <%= render "users/education" %>
        <%= render "users/experience" %>
        <!-- Sticky Block End Point -->
        <div id="stickyBlockEndPoint"></div>
      </div>
    </div>
    <!-- End Row -->
  </div>
</main>
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "libraries/hs-sticky-block.min" %>
  <script type="text/javascript" charset="utf-8">
      // initialization of sticky blocks
      $('.js-sticky-block').each(function () {
          var stickyBlock = new HSStickyBlock($(this)).init();
      });
  </script>
<% end %>

app/views/users/edit_password.html.erb
<main id="content" role="main" class="bg-light">
  <!-- Breadcrumb Section -->
  <div class="bg-navy">
    <div class="container space-1 space-top-lg-2 space-bottom-lg-3">
      <div class="row align-items-center">
        <div class="col">
          <div class="d-none d-lg-block">
            <h1 class="h2 text-white">Personal info</h1>
          </div>

          <!-- Breadcrumb -->
          <ol class="breadcrumb breadcrumb-light breadcrumb-no-gutter mb-0">
            <li class="breadcrumb-item">Account</li>
            <li class="breadcrumb-item active" aria-current="page">Update Password</li>
          </ol>
          <!-- End Breadcrumb -->
        </div>

        <div class="col-auto">
          <div class="d-none d-lg-block">
            <a class="btn btn-soft-light" href="<%= destroy_user_session_path %>">Log out</a>
          </div>

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn btn-icon btn-sm rounde-circle d-lg-none"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="sidebarNav"
                  data-toggle="collapse"
                  data-target="#sidebarNav">
              <span class="navbar-toggler-default">
                <i class="fas fa-bars"></i>
              </span>
            <span class="navbar-toggler-toggled">
                 <i class="fas fa-times"></i>
              </span>
          </button>
          <!-- End Responsive Toggle Button -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Breadcrumb Section -->

  <!-- Content Section -->
  <div class="container space-2 space-top-lg-0 mt-lg-n10">
    <div class="row">
      <div class="col-lg-3">
        <!-- Navbar -->
        <%= render "layouts/sidenav" %>
        <!-- End Navbar -->
      </div>

      <div class="col-lg-9">
        <!-- Card -->
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Update Password</h5>
          </div>

          <!-- Body -->
          <div class="card-body">
            <%= form_for(@user, local: true, url: update_password_users_path, html: {method: :put}) do |f| %>
              <% error_messages = @user.errors.messages %>
              <!-- Form Group -->
              <div class="row form-group">
                <label class="col-sm-3 col-form-label input-label">
                  Password
                </label>
                <div class="col-sm-9">
                  <%= f.password_field :password, autofocus: true, autocomplete: "new-password", class: 'form-control', type: 'password' %>
                  <% if error_messages[:password] %>
                    <div class="field-error">
                      <%= error_messages[:password][0] %>
                    </div>
                  <% end %>
                </div>
              </div>
              <!-- End Form Group -->

              <!-- Form Group -->
              <div class="row form-group">
                <label class="col-sm-3 col-form-label input-label">
                  Password confirmation
                </label>
                <div class="col-sm-9">
                  <%= f.password_field :password_confirmation, autofocus: true, autocomplete: "password_confirmation", class: 'form-control', type: 'password' %>
                  <% if error_messages[:password_confirmation] %>
                    <div class="field-error">
                      <%= error_messages[:password_confirmation][0] %>
                    </div>
                  <% end %>
                </div>
              </div>
              <!-- End Form Group -->

              <!-- Form Group -->
              <div class="row form-group">
                <label class="col-sm-3 col-form-label input-label">
                  Current Password
                </label>
                <div class="col-sm-9">
                  <%= f.password_field :current_password, autofocus: true, autocomplete: "current_password", class: 'form-control', type: 'password' %>
                  <% if error_messages[:current_password] %>
                    <div class="field-error">
                      <%= error_messages[:current_password][0] %>
                    </div>
                  <% end %>
                </div>
              </div>
              <!-- End Form Group -->

              <!-- Footer -->
              <div class="card-footer d-flex justify-content-end">
                <%= link_to "Back", details_users_path, type: 'button', class: 'btn btn-white mr-2' %>
                <%= f.submit "Update", class: 'btn btn-primary' %>
              </div>
              <!-- End Footer -->
            <% end %>
          </div>
        </div>
        <!-- End Row -->
      </div>
      <!-- End Content Section -->
    </div>
  </div>
</main>

app/views/users/upload.html.erb
<main id="content" role="main" class="bg-light">
  <!-- Breadcrumb Section -->
  <div class="bg-navy">
    <div class="container space-1 space-top-lg-2 space-bottom-lg-3">
      <div class="row align-items-center">
        <div class="col">
          <div class="d-none d-lg-block">
            <h1 class="h2 text-white">Personal info</h1>
          </div>

          <!-- Breadcrumb -->
          <ol class="breadcrumb breadcrumb-light breadcrumb-no-gutter mb-0">
            <li class="breadcrumb-item">Account</li>
            <li class="breadcrumb-item active" aria-current="page">Update Profile Picture</li>
          </ol>
          <!-- End Breadcrumb -->
        </div>

        <div class="col-auto">
          <div class="d-none d-lg-block">
            <a class="btn btn-soft-light" href="<%= destroy_user_session_path %>">Log out</a>
          </div>

          <!-- Responsive Toggle Button -->
          <button type="button" class="navbar-toggler btn btn-icon btn-sm rounde-circle d-lg-none"
                  aria-label="Toggle navigation"
                  aria-expanded="false"
                  aria-controls="sidebarNav"
                  data-toggle="collapse"
                  data-target="#sidebarNav">
              <span class="navbar-toggler-default">
                <i class="fas fa-bars"></i>
              </span>
            <span class="navbar-toggler-toggled">
                 <i class="fas fa-times"></i>
              </span>
          </button>
          <!-- End Responsive Toggle Button -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Breadcrumb Section -->

  <!-- Content Section -->
  <div class="container space-2 space-top-lg-0 mt-lg-n10">
    <div class="row">
      <div class="col-lg-3">
        <!-- Navbar -->
        <%= render "layouts/sidenav" %>
        <!-- End Navbar -->
      </div>

      <div class="col-lg-9">
        <!-- Card -->
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Update Profile Picture</h5>
          </div>
          <%= form_for(@user, local: true, url: do_upload_users_path, html: {method: :put}) do |f| %>
            <% error_messages = @user.errors.messages %>
            <!-- Body -->
              <div class="card-body upload-overflow">
                <div>
                  <%= f.file_field :file %>
                </div>
                <% if error_messages[:file] %>
                  <%= error_messages[:file][0] %>
                <% end %>
                <div>
                  <% if current_user.avatar_image.attached? %>
                    <%= image_tag current_user.avatar_image.variant(resize_to_fit: [1280, 720]) %>
                  <% end %>
                </div>
              </div>
              <!-- End Body -->

              <!-- Footer -->
              <div class="card-footer d-flex justify-content-end">
                <%= link_to "Back", details_users_path, type: 'button', class: 'btn btn-white mr-2' %>
                <%= f.submit "Update", type: 'submit', class: 'btn btn-primary' %>
              </div>
              <!-- End Footer -->
          <% end %>
        </div>
            <!-- End Card -->
      </div>
      <!-- End Row -->
    </div>
    <!-- End Content Section -->
  </div>
</main>