config/routes.rb
Rails.application.routes.draw do
  # Routes for admin pages
	namespace :admin do
		resources :courses, only: [:index, :show] do
			get :approve
			get :disapprove
    end
    resources :categories
  end

	# Routes for on-boarding Rails pages
	namespace :teaching do
  	resources :courses do
  		collection do
  			get :start_teaching
      end
			resources :enrollments, only: [] do
				collection do
					get :bulk_enrollment
					post :enroll_users
					get :requests
				end
				get :accept
				get :decline
			end
			resources :chapters, except: [:index] do
				resources :course_contents, except: [:index]
				resources :assignments do
					get :answers
				end
      end
  	end
  end

  match "zohoverify/verifyforzoho", to: 'home_page#verify', :via => [:get]

  devise_for :users, controllers: {
  	registrations: 'registrations',
  	sessions: 'sessions',
  	passwords: 'passwords',
  	confirmations: 'confirmations'
  }
  resources :users, only: [] do
  	collection do
      get :edit_password
      put :update_password
  		get :cancel_account
  		get :details
  		get :upload
  		put :do_upload
  	end
  end
	resources :notebooks, except: [:show] do
		resources :notes, except: [:show]
	end

  # Routes for API
  namespace :trading do
  	resources :stocks, :only => [:index, :show, :edit, :update] do
  		get :earning_date_history
  		get :price_history
  		post :import_earning_date_history
  		post :import_price_history
  		resources :analysis, only: [:index]
  		resources :traffics, only: [:index]
  	end

  	resources :sites do
  		get :static, on: :collection
  		resources :site_histories
  	end  	
  end

	namespace :api, constraints: { format: 'json' } do
		resources :courses, only: [:index, :show] do
			resources :conversations do
				collection do
					post :create_group
				end
				get :messages
				post :update_members
			end
			get :conversation_details
			post :enrollment_request
			collection do
				get :enrolled
      end
      resources :chapters, only: [] do
				resources :assignment_submissions, only: [:update] do
					get :find_or_create, on: :collection
				end
      end
    end
		resources :qualifications, only: [:index, :create, :update, :destroy]
		resources :reviews
    	resources :conversations, only: [] do
			resources :messages
		end
		resources :calls, only: [:create] do
      match '/:user_id/join/:calling_code', to: 'calls#join', on: :collection, :via => [:get, :post]
		end
		resources :users, only: [] do
			collection do
				get :current_user_info
				get '/:conversation_id/mark_messages_read', to: 'users#mark_messages_read'
			end
    end
    resources :enquiries, only: [:create]
	end
	root :to => 'home_page#index'
	mount ActionCable.server => '/cable'
	get '/*path', to: 'home_page#index', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses
	scope :active, -> { where(active: true) }

	validates :title, presence: true

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to admin_category_path(@category), notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_category_path(@category), notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_categories_url, notice: 'Category was successfully deleted.'
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category], local: true) do |form| %>
  <% error_messages = category.errors.messages %>
  <div class="pl-4 pr-4 space-top-1">
    <div class="form-group">
      <label class="input-label" for="full_name"> <%= form.label :title %></label>
      <%= form.text_field :title, autofocus: true, autocomplete: "full_name", class: 'form-control', type: 'text', id: 'full_name', placeholder: 'Title' %>
      <% if error_messages[:title] %>
        <div class="field-error">
          <%= error_messages[:title][0] %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <label class="input-label" for="description"> <%= form.label :description %></label>
      <%= form.text_area :description, class: 'form-control', id: 'description', placeholder: 'Description' %>
    </div>
    <!-- Button -->
    <div class="row align-items-center mb-5 ">
      <div class="col-6 mb-sm-0 pl-4">
        <%= link_to "Cancel", admin_categories_path, class: 'font-size-1 font-weight-bold text-muted content-centered' %>
        <% if params[:action] == "edit" %>
          <%= link_to 'View', admin_category_path(category: @category), class: 'font-size-1 font-weight-bold text-muted pl-md-4 pl-2' %>
        <% end %>
      </div>
      <div class="col-6 text-right">
        <%= form.submit "Save", class: "btn btn-sm btn-primary" %>
      </div>
    </div>
    <!-- End Button -->
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
          <li class="breadcrumb-item"><a href="<%= admin_categories_path %>" class="text-light text-highlight-light">Category</a></li>
          <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <!-- Card -->
  <div class="card mx-auto w-lg-60">
    <!-- Form -->
    <%= render 'form', category: @category %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute top-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path("components/dots-3.svg") %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>

app/views/admin/categories/index.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero" >
  <div class="container space-1">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">Categories</span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <div class="text-right mx-lg-auto space-bottom-1">
    <button type="button" class="btn btn-xs btn-primary">
      <%= link_to 'New Category', new_admin_category_path, class: 'text-white font-weight-bold' %>
      <i class="fas fa-plus ml-1"></i>
    </button>
  </div>
  <!-- Card -->
  <% if @categories.present? %>
    <div class="card mx-lg-auto">
      <!-- Table -->
      <div class="table-responsive">
        <table class="table table-align-middle table-borderless table-thead-bordered table-nowrap">
          <thead class="thead-light">
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>No of courses</th>
            <th colspan='3'>Action</th>
          </tr>
          </thead>
          <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td>
                <%= category.title %>
              </td>
              <td><%= category.description %></td>
              <td><%= category.courses.count %></td>
              <td>
                <%= link_to 'View', admin_category_path(category), class: 'btn btn-xs btn-outline-success' %>
              </td>
              <td>
                <%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-xs btn-outline-success' %>
              </td>
              <td>
                <%= link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: 'Are you sure you want to delete this category?'}, class: 'btn btn-xs btn-outline-danger' %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <!-- End Table -->
      </div>
      <!-- End Card -->
      <!-- SVG Elements -->
      <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
        <div class="mb-n7 mr-n7">
          <img class="img-fluid" src="<%= asset_path("components/dots-5.svg") %>" alt="Image Description">
        </div>
      </figure>
      <!-- End SVG Elements -->
    </div>
  <% else %>
    <div class="card mx-lg-auto">
      <!-- Search -->
      <div class="container space-2">
        <div class="row justify-content-md-between align-items-md-center pl-4 pr-4">
          <div class="col-md-5 mb-3 mb-md-0 text-align-middle">
            <figure class="max-w-8rem mx-auto">
              <img class="img-fluid" src="<%= asset_path('icons/icon-36.svg') %>" alt="SVG">
            </figure>
          </div>

          <div class="col-md-7 col-lg-6">
            <div class="row justify-content-md-between align-items-md-center">
              <div class="col-lg-12  space-bottom-1">
                <h4 class="h5 mb-0 text-muted">Looks Like there are no categories here!</h4>
              </div>
              <div class="col-lg-12 ">
                <form class="input-group input-group-merge">
                  <input type="search" class="form-control" placeholder="Find a course" aria-label="Find a course" aria-describedby="searchApp">
                  <div class="input-group-append">
                    <span class="input-group-text" id="searchApp">
                      <i class="fas fa-search"></i>
                    </span>
                  </div>
                </form>
              </div>
              <div class="col-lg-12 space-top-1 text-right">
                <%= link_to "Go Home", root_path, class: 'font-size-1 btn btn-ghost-primary' %>
              </div>
            </div>
            <!-- Input -->
            <!-- End Input -->
          </div>
        </div>
      </div>
      <!-- End Search -->
    </div>
  <% end %>
</div>

<% content_for :javascript_includes do %>
  <%= javascript_include_tag "jquery_ujs" %>
<% end %>

app/views/admin/categories/new.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
          <li class="breadcrumb-item"><a href="<%= admin_categories_path %>" class="text-light text-highlight-light">Category</a></li>
          <li class="breadcrumb-item active" aria-current="page">New</li>
        </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <!-- Card -->
    <div class="card mx-auto w-lg-60">
      <!-- Form -->
      <%= render 'form', category: @category %>
      <!-- End Card -->
      <!-- SVG Elements -->
      <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
        <div class="mb-n7 mr-n7">
          <img class="img-fluid" src="<%= asset_path("components/dots-5.svg") %>" alt="Dots">
        </div>
      </figure>
      <!-- End SVG Elements -->
    </div>
</div>

app/views/admin/categories/show.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
          <li class="breadcrumb-item"><a href="<%= admin_categories_path %>" class="text-light text-highlight-light">Category</a></li>
          <li class="breadcrumb-item active" aria-current="page">Detail</li>
        </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <!-- Card -->
  <div class="card mx-auto w-lg-60 pl-4 pr-4 space-top-1">
    <div class="row">
      <div class="col-12 space-bottom-1">
        <div class="row">
          <div class="col-4 text-muted">Title</div>
          <div class="col-8 text-dark"><%= @category.title %></div>
        </div>
      </div>
      <div class="col-12 space-bottom-1">
        <div class="row">
          <div class="col-4 text-muted">Description</div>
          <div class="col-8 text-dark"><%= @category.description %></div>
        </div>
      </div>
      <div class="col-12 space-bottom-1">
        <div class="row">
          <div class="col-4 text-muted">List Of Courses</div>
          <div class="col-8">
            <% if @category.courses.present? %>
              <div class="table-responsive">
                <table class="table table-align-middle table-bordered table-nowrap">
                  <tbody>
                  <% @category.courses.each do |course| %>
                    <tr>
                      <td>
                        <%= link_to course.title, "/courses/#{course.id}", target: '_blank', class: 'mdc-button mdc-button__label' %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
                <!-- End Table -->
              </div>
            <% else %>
              Empty
            <% end %>

          </div>
        </div>
      </div>
    </div>
    <!-- Button -->
    <div class="row align-items-center mb-5">
      <div class="col-6 mb-sm-0 pl-4">
        <%= link_to "Back", admin_categories_path, class: 'font-size-1 font-weight-bold text-muted content-centered' %>
      </div>
      <div class="col-6 text-right">
        <%= link_to "Edit", edit_admin_category_path(@category), class: 'btn btn-sm btn-primary' %>
      </div>
    </div>
    <!-- End Button -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute top-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path("components/dots-3.svg") %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
    <!-- End Card -->
  </div>
</div>