config/routes.rb
Rails.application.routes.draw do
  # Routes for admin pages
	namespace :admin do
		resources :courses, only: [:index, :show] do
			get :approve
			get :disapprove
    end
    resources :categories
  end

	# Routes for on-boarding Rails pages
	namespace :teaching do
  	resources :courses do
  		collection do
  			get :start_teaching
      end
			resources :enrollments, only: [] do
				collection do
					get :bulk_enrollment
					post :enroll_users
					get :requests
				end
				get :accept
				get :decline
			end
			resources :chapters, except: [:index] do
				resources :course_contents, except: [:index]
				resources :assignments do
					get :answers
				end
      end
  	end
  end

  match "zohoverify/verifyforzoho", to: 'home_page#verify', :via => [:get]

  devise_for :users, controllers: {
  	registrations: 'registrations',
  	sessions: 'sessions',
  	passwords: 'passwords',
  	confirmations: 'confirmations'
  }
  resources :users, only: [] do
  	collection do
      get :edit_password
      put :update_password
  		get :cancel_account
  		get :details
  		get :upload
  		put :do_upload
  	end
  end
	resources :notebooks, except: [:show] do
		resources :notes, except: [:show]
	end

  # Routes for API
  namespace :trading do
  	resources :stocks, :only => [:index, :show, :edit, :update] do
  		get :earning_date_history
  		get :price_history
  		post :import_earning_date_history
  		post :import_price_history
  		resources :analysis, only: [:index]
  		resources :traffics, only: [:index]
  	end

  	resources :sites do
  		get :static, on: :collection
  		resources :site_histories
  	end  	
  end

	namespace :api, constraints: { format: 'json' } do
		resources :courses, only: [:index, :show] do
			resources :conversations do
				collection do
					post :create_group
				end
				get :messages
				post :update_members
			end
			get :conversation_details
			post :enrollment_request
			collection do
				get :enrolled
      end
      resources :chapters, only: [] do
				resources :assignment_submissions, only: [:update] do
					get :find_or_create, on: :collection
				end
      end
    end
		resources :qualifications, only: [:index, :create, :update, :destroy]
		resources :reviews
    	resources :conversations, only: [] do
			resources :messages
		end
		resources :calls, only: [:create] do
      match '/:user_id/join/:calling_code', to: 'calls#join', on: :collection, :via => [:get, :post]
		end
		resources :users, only: [] do
			collection do
				get :current_user_info
				get '/:conversation_id/mark_messages_read', to: 'users#mark_messages_read'
			end
    end
    resources :enquiries, only: [:create]
	end
	root :to => 'home_page#index'
	mount ActionCable.server => '/cable'
	get '/*path', to: 'home_page#index', constraints: lambda { |req|
		req.path.exclude? 'rails/active_storage'
	}
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :course
  has_many :course_contents
  has_many :assignments
  validates :title, presence: true
end

app/controllers/teaching/assignments_controller.rb
class Teaching::AssignmentsController < Teaching::BaseController
  before_action :set_course_and_chapter
  before_action :set_assignment, only: [:show, :edit, :update, :destroy, :answers]

  def index
    @assignments = @chapter.assignments
  end

  def show
  end

  def new
    @assignment = @chapter.assignments.new
  end

  def edit
  end

  def create
    @assignment = @chapter.assignments.new(assignment_params)
    if @assignment.save
      redirect_to teaching_course_path(@course), notice: 'Assignment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @assignment.update(assignment_params)
      redirect_to teaching_course_path(@course), notice: 'Assignment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @assignment.destroy
    redirect_to teaching_course_path(@course), notice: 'Assignment was successfully deleted.'
  end

  def answers
    @submissions = @assignment.assignment_submissions
  end

  private
  def set_assignment
    assignment_id = params[:id] || params[:assignment_id]
    @assignment = @chapter.assignments.find(assignment_id)
  end

  def assignment_params
    params.require(:assignment).permit(:question, :instructions, :points, :due_date, :chapter_id)
  end
end

app/controllers/teaching/base_controller.rb
class Teaching::BaseController < ApplicationController
	before_action :authenticate_user!

	protected
	def set_course_and_chapter
		set_owned_course
		@chapter = @course.chapters.find(params[:chapter_id])
	end
end

app/controllers/teaching/chapters_controller.rb
class Teaching::ChaptersController < Teaching::BaseController
  before_action :set_owned_course
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  def new
    @chapter = @course.chapters.new
  end

  def edit
  end

  def show
  end

  def create
    @chapter = @course.chapters.new(chapter_params)

    if @chapter.save
      redirect_to new_teaching_course_chapter_course_content_path(@course, @chapter), notice: 'Chapter was successfully created.'
    else
      render :new
    end
  end

  def update
    if @chapter.update(chapter_params)
      redirect_to new_teaching_course_chapter_course_content_path(@course, @chapter), notice: 'Chapter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    redirect_to teaching_course_path(@course), notice: 'Chapter was successfully deleted.'
  end

  private
  def set_chapter
    @chapter = @course.chapters.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:title)
  end
end

app/controllers/teaching/course_contents_controller.rb
class Teaching::CourseContentsController < Teaching::BaseController
  before_action :set_course_and_chapter
  before_action :set_course_content, only: [:show, :edit, :update, :destroy]

  def new
    @course_content = @chapter.course_contents.new
  end

  def edit
  end

  def create
    @course_content = @chapter.course_contents.new(course_content_params)

    respond_to do |format|
      if @course_content.save
        format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully created.' }
        format.json { render :show, status: :created, location: @course_content }
      else
        format.html { render :new }
        format.json { render json: @course_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course_content.update(course_content_params)
        format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_content }
      else
        format.html { render :edit }
        format.json { render json: @course_content.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course_content.destroy
    respond_to do |format|
      format.html { redirect_to teaching_course_path(@course), notice: 'Course content was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_course_content
      @course_content = @chapter.course_contents.find(params[:id])
    end

    def course_content_params
      params.require(:course_content).permit(:title, :description, :duration, :preview)
    end
end

app/controllers/teaching/courses_controller.rb
class Teaching::CoursesController < Teaching::BaseController
  before_action :authenticate_user!, except: [:show, :start_teaching]
  before_action :set_owned_course, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create, :edit, :update]

  def index
    @courses = current_user.courses.includes(:category)
  end

  def show
    @course = Course.find(params[:id])
    @chapters = @course.chapters.includes(:course_contents).includes(:assignments)
  end

  def new
    @course = current_user.courses.new
  end

  def edit
  end

  def start_teaching
    if user_signed_in? && !current_user.has_qualifications?
      redirect_to REACT_ROUTES[:qualifications]
    end
  end

  def create
    @course = current_user.courses.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to new_teaching_course_chapter_path(@course), notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to new_teaching_course_chapter_path(@course), notice: 'Course was successfully updated.' }
        format.json { render json: @course, status: :updated }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to teaching_courses_url, notice: 'Course was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
  def course_params
    params.require(:course).permit(:title, :body, :website, :course_for, :price, :category_id, :cover_image, :short_description, :course_highlights, :duration, :no_of_lessons, :level, :discount_percentage)
  end

  def set_categories
    @categories = Category.active
    @levels = [["All levels", ""], ["Beginner", "Beginner"], ["Advanced", "Advanced"], ["Intermediate", "Intermediate"]]
  end
end

app/controllers/teaching/enrollments_controller.rb
class Teaching::EnrollmentsController < Teaching::BaseController
  before_action :set_owned_course
  before_action :set_enroll_request, only: [:accept, :decline]

  def accept
    @enroll_request.approve
    @enroll_request.course.enroll_in_general_conversation(@enroll_request.user)
    flash[:notice] = "The enrollment request is approved."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def decline
    @enroll_request.destroy
    flash[:notice] = "The enrollment request is declined."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def bulk_enrollment

  end

  def enroll_users
    records_created = []
    records_failed = []
    params[:enroll_request].each do |key, enroll_request_params|
      enroll_request = @course.enroll_requests.create(allowed_enroll_request_params(enroll_request_params))
      if enroll_request.persisted?
        records_created << enroll_request.email
      else
        records_failed << enroll_request.email
      end
    end
    created_count = records_created.count
    flash[:notice] = "#{created_count} #{'request'.pluralize(created_count)} #{created_count == 1 ? 'is' : 'are'} sent(#{records_created.join(", ")}). #{records_failed.count} didn't succeed."
    redirect_to requests_teaching_course_enrollments_path(@course)
  end

  def requests
    @enroll_user_requests = @course.enroll_requests
  end

  private

  def set_enroll_request
    @enroll_request = @course.enroll_requests.find(params[:enrollment_id])
  end

  def allowed_enroll_request_params(enroll_request_params)
    enroll_request_params.permit(:full_name, :email, :phone)
  end
end

app/views/teaching/chapters/_chapter_block.html.erb
<div class="p-3">
  <%= render "teaching/course_contents/index", :course_contents => chapter.course_contents, :chapter => chapter %>
  <%= render "teaching/assignments/index", :assignments => chapter.assignments, :chapter => chapter %>
  <div class="border mb-2">
    <div class="card-header">
      <div class="media-body">
        <h5 class="mb-0"><i class="fas fa-pencil-alt pt-1 mr-2 text-body"></i>Quiz</h5>
      </div>
      <span>
       <a href="/quizzes/index" class="btn btn-xs btn-soft-primary"  data-toggle="tooltip" data-html="true" title="Add New Quiz">
          <i class="fas fa-plus"></i>
        </a>
    </span>
    </div>
  </div>

</div>

app/views/teaching/chapters/_form.html.erb
<%= form_with(model: [:teaching, @course, @chapter]) do |form| %>
  <% error_messages = @chapter.errors.messages %>
  <div class="pl-4 pr-4 space-top-1">
    <div class="row">
      <div class="col-sm-12 form-group">
        <label class="input-label" for="full_name"> <%= form.label :title %></label>
        <%= form.text_field :title, class:'form-control' %>
        <% if error_messages[:title] %>
          <div class="field-error">
            <%= error_messages[:title][0] %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row align-items-center mb-5 mt-4">
      <div class="col-6 mb-sm-0 pl-4">
        <%= link_to "Back", teaching_course_path(@course), class: 'font-size-1 font-weight-bold text-muted content-centered' %>
      </div>
      <div class="col-6 text-right">
        <%= form.submit "Save", class: "btn btn-sm btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/teaching/chapters/_index.html.erb
<div class="card mb-3 mb-lg-5">
  <div class="card-header">
    <h5 class="card-title">

      </i>Chapters
    </h5>
    <span>
        <a href="<%= new_teaching_course_chapter_path(@course) %>" class="btn btn-xs btn-no-focus btn-primary">
          <i class="fas fa-plus mr-1"></i>
           Add New Chapter
        </a>
    </span>
  </div>
  <div class="card-body">
    <% @chapters.each do |chapter| %>
      <div id="basicsAccordion">
        <div class="border mb-3">
          <div class="card-header p-3">
            <div class="media-body ml-3">
              <h4 class="mb-0"><%= chapter.title %></h4>
              <small class="d-block smal text-cap"><%= pluralize(chapter.course_contents.count, 'lecture') %></small>
            </div>
            <span>
              <a href="<%=teaching_course_chapter_path(@course, chapter) %>" class="btn btn-ghost-info btn-xs" data-toggle="tooltip" data-html="true" title="View" data-placement="top">
                  <i class="fas fa-eye"></i>
                </a>
               <a href="<%= edit_teaching_course_chapter_path(@course, chapter) %>" class="btn btn-ghost-info btn-xs mr-1" data-toggle="tooltip" data-html="true" title="Edit" data-placement="top">
                  <i class="fas fa-pen"></i>
                </a>
               <a href="<%=  teaching_course_chapter_path(@course, chapter) %>" data-method="delete" data-confirm="Are you sure you want to delete this chapter?" class="btn btn-ghost-danger btn-xs" data-toggle="tooltip" data-html="true" title="Delete" data-placement="top">
                  <i class="fas fa-trash"></i>
                </a>
            </span>
          </div>
          <div>
            <%= render "teaching/chapters/chapter_block", :chapter => chapter %>
          </div>
        </div>
      </div>
      <div class="text-center mb-4">
        <span class="divider divider-text"></span>
      </div>
    <% end %>
  </div>
</div>

app/views/teaching/chapters/edit.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
           <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
          <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
          <li class="breadcrumb-item active" aria-current="page">Edit <%= @chapter.title %></li>
        </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto w-lg-60">
    <!-- Form -->
    <%= render 'form', chapter: @chapter %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path('components/dots-3.svg') %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>

app/views/teaching/chapters/new.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
         <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
            <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
            <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
            <li class="breadcrumb-item active" aria-current="page">New Chapter</li>
          </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto w-lg-60">
    <!-- Form -->
    <%= render 'form', chapter: @chapter %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path('components/dots-3.svg') %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>

app/views/teaching/chapters/show.html.erb
<!-- Hero Section -->
<div class="bg-navy bg-img-hero">
  <div class="container space-1 ">
    <div class="w-lg-65 text-center mx-lg-auto">
      <span class="badge badge-soft-light badge-pill font-size-1 py-3 px-4 mb-3">
       <nav aria-label="breadcrumb">
          <ol class="breadcrumb breadcrumb-light breadcrumb-no-margin">
            <li class="breadcrumb-item"><a href="<%= teaching_courses_path %>" class="text-light text-highlight-light">My Courses</a></li>
            <li class="breadcrumb-item"><a href="<%= teaching_course_path(@course) %>" class="text-light text-highlight-light"><%= @course.title %></a></li>
            <li class="breadcrumb-item active" aria-current="page"><%= @chapter.title %></li>
          </ol>
        </nav>
      </span>
    </div>
  </div>
</div>
<!-- End Hero Section -->

<div class="container space-1">
  <%= render "layouts/steps" %>
  <!-- Card -->
  <div class="card mx-auto">
    <!-- Form -->
    <%= render "teaching/chapters/chapter_block", :chapter => @chapter %>
    <!-- End Card -->
    <!-- SVG Elements -->
    <figure class="max-w-19rem w-100 position-absolute bottom-0 right-0 z-index-n1 hide-svg">
      <div class="mb-n7 mr-n7">
        <img class="img-fluid" src="<%= asset_path("components/dots-3.svg") %>" alt="Image Description">
      </div>
    </figure>
    <!-- End SVG Elements -->
  </div>
</div>